### ISSUE TITLE
Issue with EOL parsing.

### ISSUE THREAD

**Issue by tabarra** [nebrelbug/squirrelly#117]
**Describe the bug**
The library seems to be ignoring LF as line endings.

**To Reproduce**
Consider this code:
```javascript
datasets: [{
    //Change squirrelly tag: {{tags(--,--)/}}
    data: --chartData|safe--
    //Changing it back: --tags({{,}})/--
}]
```

**Expected behavior**
```javascript
datasets: [{
    //Change squirrelly tag: 
    data: example
    //Changing it back: 
}]
```

**Output received**
```javascript
datasets: [{
    //Change squirrelly tag:     data: example    //Changing it back: }]
```

**Browser [e.g. chrome, safari]**
Any

**Additional context**
Works perfectly when the template is using CRLF.

**Comment by nebrelbug** [comment]
Hi @tabarra thanks for opening the issue!

Squirrelly is set to remove `\n` if it follows `[tagOpen]content[tagClose]`, but not `\r\n`.

Since LF just uses `\n`, Squirrelly will replace the newline right after a tag, so `{{myTag}}\n` will become `options.myTag`. But with CRLF, `\n` doesn't directly follow the tag, it follows `\r`, so it's not replaced.

Since Squirrelly only replaces the first newline, you can write:
```
datasets: [{
    //Change squirrelly tag: {{tags(--,--)/}}

    data: --chartData|safe--

    //Changing it back: --tags({{,}})/--

}]
```

This issue will be resolved in version 8, where you'll have more control over whitespace

**Comment by nebrelbug** [comment]
By the way, were you able to try out my tip in #115?

**Comment by tabarra** [comment]
Thank you for the reply.  
Closing this issue :)
